Build linux/macos arm64/aarch64 wheels on native runners (#1308)
+ Various CI speedups

- Switch to official PyPA build frontend for sdist ref https://pypi.org/project/build/
- Cancel running jobs when a new commit is pushed to a PR ref https://stackoverflow.com/questions/66335225#comment133398800_72408109
- Switch from setup-python to setup-uv ref https://github.com/astral-sh/setup-uv

+ Pin runner images to avoid CI rot

ref https://github.com/MagicStack/asyncpg/actions/runs/22286259051/job/64465189709?pr=1308

failed with:

======================================================================
ERROR: test_tls_version (test_connect.TestSSLConnection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/asyncpg/asyncpg/asyncpg/_testbase/__init__.py", line 92, in wrapper
    self.loop.run_until_complete(coro)
  File "/Applications/Xcode_16.4.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/runner/work/asyncpg/asyncpg/tests/test_connect.py", line 2024, in test_tls_version
    await self.connect(
  File "/Users/runner/work/asyncpg/asyncpg/asyncpg/connection.py", line 2443, in connect
    return await connect_utils._connect(
  File "/Users/runner/work/asyncpg/asyncpg/asyncpg/connect_utils.py", line 1209, in _connect
    addrs, params, config = _parse_connect_arguments(**kwargs)
  File "/Users/runner/work/asyncpg/asyncpg/asyncpg/connect_utils.py", line 893, in _parse_connect_arguments
    addrs, params = _parse_connect_dsn_and_args(
  File "/Users/runner/work/asyncpg/asyncpg/asyncpg/connect_utils.py", line 798, in _parse_connect_dsn_and_args
    ssl.minimum_version = _parse_tls_version(
  File "/Applications/Xcode_16.4.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 586, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
ValueError: Unsupported protocol version 0x304

+ Build Windows ARM64 wheels on native runner

---------

Co-authored-by: Elvis Pranskevichus <el@prans.net>